### ISSUE TITLE
Should Kakadu be optional in setup.py? 

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#109]
Maybe `--with-kdu` or `--with-opj` and neither by default?

**Comment by jpstroop** [comment]
@regisrob -- Any opinions about this? I'm really not sure what's the right thing. I know you have to do a custom build of kakadu; would it be easier if kakadu was just out of the way by default? Do you think it's worth it?

**Comment by regisrob** [comment]
I understand the reason why kakadu is set by default (which is a good reason of course), but I think I'm in favour of "neither by default" (and --with-kdu or --with-opj as arguments for setup.py install). 
Thus Loris doesn't favour any codec or format by default.
It would avoid to copy unnecessary files on the system in case you don't want to use jpeg2000 (but only tiled TIFF or static jpeg)
And a minor argument would be to prevent to overwrite previous kakadu files in /usr/local/(bin|lib) in case you didn't read really carefully the README. In this way you also avoid the risk that jp2 decoding fails silently because of the incompatibility of the kakadu bin and lib in a given environment.

**Comment by schwemmer** [comment]
The "neither by default" approach makes sense to me too, as long as it is clearly documented in the installation instructions. It seems that the following config options are currently ignored:

```
kdu_expand = '/usr/local/bin/kdu_expand' # r-x
kdu_libs = '/usr/local/lib' # r--
```

Is this correct? The Kakadu executables seem to be always taken from `/var/www/loris/bin/Linux/x86_64/kdu_expand`and `/var/www/loris/lib/Linux/x86_64/`. The supplied Kakadu version 7.2 doesn't work on Debian due to glibc version incompatibility.

I wonder if the following procedure wouldn't be easier for setup: 
- When running test.py check if OpenJPEG or Kakadu was selected. The first time this would fail and output a message telling the user to set either OpenJPEG or Kakadu in the config file (Kakadu recommended)
- When Kakadu was selected, check whether the kdu_expand and kdu_libs config options were set. By default they would be empty and have a comment "/path/to/kdu_expand" and "/path/to/kdu.so". The test would fail and output "no Kakadu found - please update the kdu_expand and kdu_libs config options in etc/loris2.conf to point to your Kakadu exectuables".
-  If the aforementioned config options were set, let Loris use these executables and check if the image transformation was successful, otherwise output "Kakadu does not seem to work properly, please check your executables under `<insert path from kdu_expand config option>`"

Or something similar.
