### ISSUE TITLE
"native" qualities problem

### ISSUE THREAD

**Issue by jeffreycwitt** [loris-imageserver/loris#135]
I'm not sure if this is a bug or a feature request, but I'm wondering why my Loris install doesn't seem to support "quality": "native". "native" appears to be the default quality requested by the "Mirador" image viewer, and thus the lack of support for "native" as a quality is causing me some problems, See an image profile for an image on my server here: http://images.scta.info:3000/pg-lon%2FL3r.jpg/info.json

**Comment by jpstroop** [comment]
Hi there. I assume you're running the latest version of Loris? If so, the issue is almost certainly that the version of Mirador you're using is IIIF Image API 1.1 compliant rather than 2.0. In 2.0 "native" was renamed "default".

You could run Loris 1.2.3, which is 1.1 compliant, or better, I think, would be to put in an issue over on the Mirador repo to get them to upgrade. I know that @azaroth42 already has a pull request in for Mirador 2 that will resolve this, but I'm not sure about the plans for Mirador (1).

Does that make sense?

Best,
Jon

**Comment by jeffreycwitt** [comment]
Dear Jon,

Thanks for your response. That makes a lot of sense. Thanks for your help.
I'll start playing around with Mirador 2 and see if that solves my problem.

Best wishes,

## jw

Dr. Jeffrey C. Witt
Philosophy Department
Loyola University Maryland
4501 N. Charles St.
Baltimore, MD 21210
www.jeffreycwitt.com http://www.jeffreycwitt.com/

From:  Jon Stroop notifications@github.com
Reply-To:  pulibrary/loris
<reply@reply.git
hub.com>
Date:  Thursday, October 23, 2014 at 8:47 AM
To:  pulibrary/loris loris@noreply.github.com
Cc:  Jeffrey Witt jeffreycwitt@gmail.com
Subject:  Re: [loris] "native" qualities problem (#135)

Hi there. I assume you're running the latest version of Loris? If so, the
issue is almost certainly that the version of Mirador you're using is IIIF
Image API 1.1 compliant rather than 2.0. In 2.0 "native" was renamed
"default".

You could run Loris 1.2.3, which is 1.1 compliant, or better, I think, would
be to put in an issue over on the Mirador repo to get them to upgrade. I
know that @azaroth42 https://github.com/azaroth42  already has a pull
request in for Mirador 2 that will resolve this, but I'm not sure about the
plans for Mirador (1).
Best,
Jon

Does that make sense?

‹
Reply to this email directly or view it on GitHub
https://github.com/pulibrary/loris/issues/135#issuecomment-60233132 .
{"@context":"http://schema.org","@type":"EmailMessage","description":"View
this Issue on 
GitHub","action":{"@type":"ViewAction","url":"https://github.com/pulibrary/l
oris/issues/135#issuecomment-60233132","name":"View Issue"}}
