### ISSUE TITLE
Percentage-Based Region Parameters Not Implemented?

### ISSUE THREAD

**Issue by sdellis** [loris-imageserver/loris#15]
The following should work:
http://example.org/image-service/abcd1234/pct:10,10,50,50/full/0/native.jpg

However, Loris returns the following error:

```
local variable 'fifo_path' referenced before assignment
```

Furthermore,  the following returns a tile that is 50x50.  

```
http://example.org/image-service/abcd1234/0,0,100,100/pct:50/0/native.jpg
```

After reading through the spec, it looks like the scaling of the tile and not the original image is intended.  However, it's difficult to create a zoom viewer without being able to manipulate the size of the image and maintain a consistent tile size.

Finally, trying to go around the problem, I noticed the following should return a 100x100 tile from the full sized image, but  for some reason returns a 7920x7920 tile (problem persists for ",3600" size, etc.) :

```
http://example.org/image-service/abcd1234/0,0,100,100/,7200/0/native.jpg
```

Creating a tile-based viewer is pretty much impossible without being able to have "non-full" parameters in both Region and Size slots.  The spec is very light on those examples and could probably be more clear.  I personally do not think that the region specified should be scaled based on the image, but perhaps there's some reason for that.

**Comment by jpstroop** [comment]
Check the spec in [4.6 Order of Implementation](http://www-sul.stanford.edu/iiif/image-api/#order). Remember that the parameters are applied in a specific order:

```
http://example.org/image-service/abcd1234/0,0,100,100/pct:50/0/native.jpg
```

_would_ return a 50x50 image because the region coordinates and width and height are always based on a full size image.

You should use 256 x 256 (or, e.g. 128, 512, 1024) tiles all the time, (so `0,0,256,256` for top left; `0,257,256,256` for the next to the right, etc.) and then use the size pct syntax like jpeg 2000 levels (100, 50, 25, 12.5, 6.25 ... ) to zoom in and out. And then, because your tile size is constant, if you're asking for a 256x256 square at pct:50, you'll know the image will be 128x128, pct:25 64x64, pct:12.5 32x32, etc. You might want to check out the javascript in the `tile_table.html` (earlier versions were doing the math to set the image width and height css, in the end I jsut let the browser do it)  and the `tile_gen()` function in `tests.py`, near the end.

I can't get anything to show up on your image server (running the tests may have screwed up the permissions on the logs? I have a solution for this and will solve it soon), but you may have found a bug with the `,7200` request; I did have a little confusion with the `convert` shellout syntax, but I thought I had it right -- in fact I was trying to not allow upsampling, so

```
http://example.org/image-service/abcd1234/0,0,100,100/,7200/0/native.jpg
```

should have thrown an error. I'll try to work on it while I'm away.

**Comment by jpstroop** [comment]
Follow up:

```
http://example.org/image-service/abcd1234/pct:10,10,50,50/full/0/native.jpg
```

style requests were broken (percentage-based region requests). Fixed in the latest revision.

**Comment by sdellis** [comment]
That all makes sense.  The existing tile-based zoom viewers all seem to maintain a constant tile size no matter what the level/scale is.  I'm having trouble tweaking that because the assumption is built into those viewers and it's a lot to untangle.  A zoom viewer can certainly be done with this API, just not exactly the way it's been done before.  So much for a quick fix.  I'm actually leaning towards building a basic custom viewer for it as a jQuery plugin (which I've already started), and basically looking at these other viewers for inspiration and functionality.

**Comment by jpstroop** [comment]
I like the idea of doing a custom viewer; why not!? 
That said, you could still maintain a constant tile size with this API if you needed to, you'd just need to ask for a bigger region. So to keep tiles at 256:

```
0,0,256,256/pct:100
0,0,512,512/pct:50
0,0,1024,1024/pct:25
0,0,2048,2048/pct:12.5
0,0,4096,4096/pct:6.25
```

i.e., every time the pct is divided by two, multiply the tile size by two.

Also, remember that the tiles at the far right edge will not necessarily be the full width (unless the image is exactly a multiple of `$tile_size` wide), and, similarly, those at the bottom might not be the full height. Again, the `tile_gen` function in `tests.py` has a pretty good algorithm for that.
