### ISSUE TITLE
Automate build and setup to work like iiify

### ISSUE THREAD

**Issue by aeschylus** [loris-imageserver/loris#174]
I recently ran across this great demo server, [iiify](https://github.com/rogerhoward/iiify). It doesn't do much, and it isn't specifically a package yet either, but I was able to simply type
`pip install Flask Pillow`
`python iiify.py`
and it worked. It was really gratifying to be immediately testing the API on my own images (though, to be fair, I did have to convert them to .jpg, since that little library doesn't support jp2). It gives the user some faith.

Ideally loris should install all its dependencies itself, so that the complete installation becomes:
`pip install loris`. Congratulations, you're now using Loris (with some sane default, letting people fix their configuration problems afterward)!

I realise this is a tall order given the Kakadu dependency, but perhaps a step in the install script can prompt the user for the path to kakadu, or it could be provided as a command line option, [similar to iipsrv](https://github.com/ruven/iipsrv#optional-libraries-kakadu).

**Comment by jpstroop** [comment]
Loris does install all of the dependencies itself--except Kakadu. The lack of a way to package Kakadu with Loris on pip is really the only thing that has kept me from making Loris installable in that way. Regarding:

> [...] or it could be provided as a command line option, similar to iipsrv.

[That's how you do it](https://github.com/loris-imageserver/loris/blob/development/doc/setup.md). If you want to get as far as the commands you posted above get you, then:

``` bash
git clone git@github.com:loris-imageserver/loris.git # I assume you had to do this 
cd loris                                             # with iffy as well
pip install -r requirements.txt
python loris.webapp.py
```

I actually prefer _not_ to document this up front ([it is documented](https://github.com/loris-imageserver/loris/blob/development/doc/develop.md), but last, if you're reading in order), because I was receiving too many  issues and emails around path or performance problems because someone was trying to run a production app using that server (by either changing the port, setting up a proxy with Apache, or something else), and it was getting frustrating. I agree that the instant gratification is nice, but, practically speaking, you shouldn't be running that server unless you're a developer.

And, what you're getting by running [`python iiify.py`](https://github.com/rogerhoward/iiify/blob/master/iiify.py#L331-L333) or  [`python loris.webapp.py`](https://github.com/loris-imageserver/loris/blob/development/loris/webapp.py#L607-L621) isn't much...it's just a single-threaded development server. You'd still need Apache, Nginx, and all of the configuration that goes with those and their WSGI modules before you could put the app into production (another reason the `pip install ...` approach doesn't actually gain you much).

**Comment by aeschylus** [comment]
Sorry to generate more of this kind of support ticket (especially since github tickets still can't be deleted). I understand the ball and chain that is an un-automatable dependency, and the tradeoff between giving people working but unclearly configured software and making them read the complete docs before attempting to deploy a production instance. 

I still think there would be value in releasing it as a pip package, and it would be smoother for developers to integrate into their own apps (even if they will need to understand the kdu_expand configuration variable).

Thank you for having very thorough documentation.

Closing.
