### ISSUE TITLE
documentation on how to set Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by jronallo** [loris-imageserver/loris#181]
I'm looking for how to set Access-Control-Allow-Origin to something other than *. I see there are some commits making CORS-related changes. I expected to find documentation on how to do this here:
https://github.com/loris-imageserver/loris/blob/development/doc/configuration.md

Is there already an option to change this setting?

My use case for needing to change this is that until we can work out some policy issues around sharing images we may not be able to set the header to "Access-Control-Allow-Origin: *" so we would like to whitelist our domains.

**Comment by ghukill** [comment]
Possibly related.  We're running Loris through Apache, and having a problem when serving the info.json across domains:

`The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.`

I've tried removing all instances where this header might be added again in the WSGI --> apache --> response hops, but I'm still getting this error.

Might it be possible to include a flag to set custom values for the Access-Control-Allow-Origin (header as @jronallo mentioned), or perhaps prevent adding it altogether?  Otherwise, we'll probably work to isolate Loris a bit more such that can finely tune the headers.  Thanks.

**Comment by schwemmer** [comment]
I have the same issue. We are setting the CORS header in Apache config (otherwise the manifest does not load in Mirador). It seems that Loris is setting CORS again and Mirador then fails to load the images with the following message:

`The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:8000' is therefore not allowed access.`

I noticed the `cors_regex = ''` setting in loris2.conf but I don't understand what I would have to set it to. What I want to do is to disable setting CORS headers in Loris because Loris is running via WSGI in Apache and Apache is already setting it. Any advice on how to do this will be appreciated. 

PS: like @jronallo I expected to find documentation on the setting here:
https://github.com/loris-imageserver/loris/blob/development/doc/configuration.md

**Comment by schwemmer** [comment]
We ended up removing the else condition from the `webapp.py` file that sets the CORS header to "*" by default.  This fix prevents the CORS header from being set if nothing is set in the `cors_regex` variable in the config file. 

We think it is better if it is only set in `webapp.py` if you explicitly set it in the config file, e.g. to "*".

**Comment by ColeDCrawford** [comment]
For me, Loris was successfully setting the CORS headers for my images and info.json files, but not for my manifest, which is why Mirador wouldn't load it. Setting `Header set Access-Control-Allow-Origin "*"` in apache.conf in the main directory added CORS to the manifest but added it again to the images, causing the multiple values error.

Fixed this by adding a new `<Directory>` in apache.conf to target just my manifest.
