### ISSUE TITLE
Sagami Scroll Demo gives a 404

### ISSUE THREAD

**Issue by clintonblackmore** [loris-imageserver/loris#294]
The description of the Loris project (at https://github.com/loris-imageserver/loris) lists two demos:

- Mentelin Bible, l. 1r
- Scroll illustrating a story about the Sagami River with OpenSeadragon

The second demo links to http://libimages1.princeton.edu/osd-demo/?feedme=pudl0123%2F8172070%2F01%2F00000001.jp2
When I follow the link, I see a viewer and inside, in dim grey text on a black background, it says, "Unable to open [object Object]: HTTP 404 attempting to load TileSource"

**Comment by jpstroop** [comment]
Thanks--I thought I knew what the issue was, and that we just needed to put a redirect in place, but it looks like the slashes are suddenly getting double escaped--I think it may just be a problem with that little demo page because we're not seeing this problem anywhere else, so I went ahead and updated the URL to have actual slashes instead.
