### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'log'

### ISSUE THREAD

**Issue by regisrob** [loris-imageserver/loris#43]
Hi Jon,

I need to run some more tests with another instance of Loris but I ran into errors while deploying the latest build: 

(Python version is 2.7.3)

"python test.py" returns:

<code>
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from tests import img_info_t
  File "/usr/local/loris-dev/src/loris/tests/img_info_t.py", line 4, in <module>
    from loris import img_info
  File "/usr/local/loris-dev/src/loris/loris/img_info.py", line 8, in <module>
    from log import get_logger
  File "/usr/local/loris-dev/src/loris/loris/log.py", line 25, in <module>
    conf_level = config.get('log', 'log_level')
  File "/usr/local/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'log'
<code>

Same error in Apache after deployment:

<code>
Traceback (most recent call last):
   File "/var/www/iiif/loris-dev/loris.wsgi", line 10, in <module>
     from loris.webapp import create_app
   File "/usr/local/loris-dev/lib/python2.7/site-packages/Loris-1.2.0-py2.7.egg/loris/webapp.py", line 26, in <module>
     from img_info import ImageInfo
   File "/usr/local/loris-dev/lib/python2.7/site-packages/Loris-1.2.0-py2.7.egg/loris/img_info.py", line 8, in <module>
     from log import get_logger
   File "/usr/local/loris-dev/lib/python2.7/site-packages/Loris-1.2.0-py2.7.egg/loris/log.py", line 25, in <module>
     conf_level = config.get('log', 'log_level')
   File "/usr/local/lib/python2.7/ConfigParser.py", line 330, in get
     raise NoSectionError(section)
 NoSectionError: No section: 'log'
</code>

Thx for your help

**Comment by jpstroop** [comment]
Hmmm....that was a bug that I thought I fixed right before the tag. Hold on...

**Comment by jpstroop** [comment]
Hmm, the `log` section is there in both the latest version on the development banch:

https://github.com/pulibrary/loris/blob/development/etc/loris.conf#L29

and in the revision that was tagged:

https://github.com/pulibrary/loris/blob/9a1e320ba4df68efb861fc56ed1a2919045f8ae0/etc/loris.conf#L29

So you're not getting a fresh `loris.conf` file. 

I just did a test on my machine, and indeed it looks like setuptools won't overwrite if the file exists. So, the safest thing to do would be for you to delete `/etc/loris/loris.conf` then run `setup.py install` and then configure. I just had a look around to see if there was a way to override this behavior (`--force` or something would be nice), but it doesn't look like it.

I'll add some info about this to the release notes. Thanks for catching it!

**Comment by regisrob** [comment]
Sorry it was my fault: I changed the conf directory and I forgot to change "prod_conf_fp" in "loris/log.py". That was the problem... But it means that test.py is testing against "/etc/loris/loris.conf" and not "etc/loris.conf", is that true ?

**Comment by jpstroop** [comment]
It's true for logging, unfortunately, and I don't like it.

https://github.com/pulibrary/loris/blob/development/loris/img_info.py#L16

I do point this out [in the README](https://github.com/pulibrary/loris/blob/development/README.md#logging), but it really does feel like a hack.

The problem right now is that loggers are instantiated at the module level, e.g.:
- https://github.com/pulibrary/loris/blob/development/loris/img.py#L19
- https://github.com/pulibrary/loris/blob/development/loris/img_info.py#L16

etc. And because of this I don't have the ability to pass `get_logger()` parameters, which means the only way to decide where to go/what to do is based on whether or not there's a file at `/etc/loris/loris.conf` or not.

There has to be a better way. I'll put in an issue for the next bit of work (likely to happen in later December...).

**Comment by jpstroop** [comment]
Submitted as issue #44

**Comment by jpstroop** [comment]
@regisrob see #44. This is in much better shape now. I will release shortly.
