### ISSUE TITLE
Pillow support instead of PIL

### ISSUE THREAD

**Issue by lfarrell** [loris-imageserver/loris#45]
More of a comment, but loris seems to work just fine with Pillow as well.  Do you all have any plans to make Pillow the default imaging library?  Thanks for such a cool project.

**Comment by jpstroop** [comment]
Thanks! You're not the first person to mention this or ask. I hadn't really considered Pillow, but it's sounding more and more like I should, especially if that's the way the Python community is trending.

Two things (one concern, one point of interest):
1. (the concern) Does Pillow play well with Little CMS? This is required for some (optional) [color profile mapping to sRGB with JP2s](https://github.com/pulibrary/loris/blob/development/loris/transforms.py#L283-L285), and I wouldn't lose that feature.
2. (the point of interest) I designed the image transformation classes to be as easy to swap in and out, reimplement, etc. as possible. As long as you implement [this interface](https://github.com/pulibrary/loris/blob/development/loris/transforms.py#L24-L39) and then [tell Loris about it in the config file](https://github.com/pulibrary/loris/blob/development/etc/loris.conf#L46-L65), any options there will show up in the config dictionary and you can do whatever you want. My reason for doing it this way was more or less exactly what you're talking about: others may prefer different imaging libraries (e.g. an earlier version of Loris shelled out to ImageMagick instead of using PIL; people who have licensed other JP2 implementations may want to build commands that worth with those, etc.).

However, as I said, if this is the way the Python community is trending...especially if Pillow is becoming the de-facto standard imaging library for Python 3, which is what some seem to be saying, then I need to look at it seriously.

So, I'm curious, when you say 'loris seems to work just fine with Pillow', what did you have to change, if anything? Did you try JP2 as well (wondering especially about [this](https://github.com/pulibrary/loris/blob/development/loris/transforms.py#L268-L274), for some reason)? Obviously I know nothing about Pillow and need to have a look. Do you have a fork I could see? Would it be (do you think) worth my making a separate transformer that uses Pillow and make it an option to use Pillow OR PIL, or can one really hop between the two seamlessly?

Thanks for getting in touch (you may be regretting it!)
-Js

**Comment by jpstroop** [comment]
Wow...five minutes to answer most of the questions I just asked you.

http://pillow.readthedocs.org/en/latest/installation.html

Pillow certainly wins the documentation round. The API seems identical; seems like I could really (in theory) just install Pillow instead of PIL and go?

**Comment by lfarrell** [comment]
It should basically be a straight port of every feature in PIL according to the authors, but with much easier installation and faster release cycles.  I did try it with JP2 and had no issues.  Admittedly my testing has been limited.  Here at UNC-Chapel Hill we were most interested in the JP2 support as we're running into issues with Djatoka.  If there are still any issues from above you're worried about I'm happy to answer.

**Comment by jpstroop** [comment]
You know, it turned out to be super easy. Because others had asked about "Pillow Support" I had assumed it was a big deal, different API, etc. There was literally one change (as far as I can tell, and assuming my test coverage is good), which was this:

https://github.com/pulibrary/loris/blob/development/loris/transforms.py#L16-L22

i.e. `ImageCms` seems to be within with the `PIL` namespace in Pillow.

So, the development branch should support Pillow now. I have a few other minor things to fix (logging is a mess at the moment) and I'll probably try to tag a minor release next week.

Note (if you're interesting in a test drive) that I've also updated the README for how to install PIllow or PIL with LittleCms support. It's annoying:

https://github.com/pulibrary/loris/blob/development/README.md#installing-pil-or-pillow

Thanks again for your interest!
