### ISSUE TITLE
OS package for Loris

### ISSUE THREAD

**Issue by lfarrell** [loris-imageserver/loris#51]
We're discussing using loris at UNC-Chapel Hill Libraries and were wondering if there was an Ubuntu or Redhat/Centos package for loris?   Our sys. admin was hoping not to have to create a local package if possible.

When you build it are you all using Ubuntu LTS or a more unstable version?

Also does loris require python 2.7?  Redhat, unfortunately is only up to python 2.6 in their releases.

thanks!

**Comment by jpstroop** [comment]
Dean,
Thanks for getting in touch! Unfortunately there's no rpm (or deb) package. Because of Kakadu's licensing terms this will probably never be possible. That said, the current development branch includes Kakadu for 64-bit Linux, so deployment is easier than it's ever been. If your admin has a 64-bit Ubuntu 12.04 LTS box and a half hour, I'd encourage them to clone the development branch and step through the [install docs](https://github.com/pulibrary/loris#installation-instructions). They're verbose, but I've been gotten a fair bit of good feedback about them lately.

(There's a new release coming soon, BTW, I'm just waiting for final approval on the language in the README from Kakadu.)

I've built Loris on Centos 5.5, but we're in production on Ubuntu 12.04 LTS here at Princeton. I've gone through all of the deployment steps on all of the Ubuntu versions since that one and it worked fine too. Loris makes heavy use of [collections.OrderedDict](http://docs.python.org/2/library/collections.html#collections.OrderedDict) for its LRU memory caches, so I'm afraid python 2.7.x is necessary. On Centos I had to install Python 2.7 manually and then make sure to use the correct executable when I installed Loris, but it wasn't a big deal at all.

Please feel free (you or your admin) to drop me a direct email if you hit a snag or have suggestions. I think you have my email from the code4lib list.

-Jon

**Comment by jpstroop** [comment]
Was about to close this, but noticed that you asked about Python 2.6. As of #110, python 2.6 is supported.

**Comment by lfarrell** [comment]
Okay, great thanks.
