### ISSUE TITLE
Original image directory

### ISSUE THREAD

**Issue by doktorbro** [loris-imageserver/loris#90]
Do you have a global option for a directory with all the original images or must the identifier contain the whole path to the image?

**Comment by jpstroop** [comment]
**Short Answer:**

Set this: https://github.com/pulibrary/loris/blob/development/etc/loris.conf#L34 

See also: https://github.com/pulibrary/loris/blob/development/doc/resolver.md

**Long Answer:**

See: https://github.com/pulibrary/loris/issues/62

I always assumed that the resolver class was something people would want to override--people will have their IDs in different databases, may wish to apply some auth business as part of the resolution process, etc.

What I should have done is set it up so that you can point to a `package.Class` in the config that implements the `AbstractResolver` class, rather than forcing you to change the class that's in the Loris source. That's the plan for 2.0.0

**Comment by doktorbro** [comment]
Thank you.
