### ISSUE TITLE
identifier/ errors

### ISSUE THREAD

**Issue by azaroth42** [loris-imageserver/loris#94]
Perhaps a spec bug, but identifier/ gives 400 rather than redirection to /info.json

**Comment by jpstroop** [comment]
Thanks, I'll check it out. Could be one of a few things (maybe my moral
opposition to the idea shining through :-)), but probably just a bug
introduced when I refactored the routing recently.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
@azaroth42, just doing some cleanup and ran across this. `/identifier/` does 404, but `/identifier` (no trailing slash) works. I suppose the friendly thing to do is to just make it work (redirect), but, for the record, we don't bring that out in the spec.

**Comment by azaroth42** [comment]
Should we fix it in the spec?

**Comment by jpstroop** [comment]
I don't think so. The presence of a trailing slash is ambiguous. However unlikely, you're in trouble if your identifier happens to end with a slash AND you chose to take this path to the info rather than `/info.json`. How does a server know when to strip it off, and when not? (current coding session is reminiscent of Easter Sunday, so it's possible I'm missing something entirely :wink:).
